Update test.yml

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -27,8 +27,8 @@ jobs:
           git add -A
           git commit -m "Release Version ${{ github.event.inputs.version }}"
           git push origin release-version-${{ github.event.inputs.version }} || {
-            echo "Release branch already exists, skipping push";
-            exit 1;
+            echo "Release branch might already exists, push failed"
+            exit 1
           }
       - name: create pull request
         run: gh pr create -B main -H release-version-${{ github.event.inputs.version }} --title 'Release Version ${{ github.event.inputs.version }}' --body 'Created by Github action'
